name: quizjatimsem2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3

  # firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.5.2
  # firebase_storage DIHAPUS — pakai Cloudinary (gratis)

  # image picker & upload ke Cloudinary
  image_picker: ^1.1.2   # ambil foto dari galeri/kamera
  http: ^1.2.2           # upload ke Cloudinary via REST API

  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/