// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbjwRL4HmEm9R26oAOaomnx8es6PNZj8o',
    appId: '1:157280276783:web:c62a33b2d2405f53e251da',
    messagingSenderId: '157280276783',
    projectId: 'quizjatim-2db59',
    authDomain: 'quizjatim-2db59.firebaseapp.com',
    storageBucket: 'quizjatim-2db59.firebasestorage.app',
    measurementId: 'G-RYRD2GVNH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx2dwnaf0UcoYwznOwRJVn262BGcwemc4',
    appId: '1:157280276783:android:a67b95501bb5dea5e251da',
    messagingSenderId: '157280276783',
    projectId: 'quizjatim-2db59',
    storageBucket: 'quizjatim-2db59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfFngcy1c1Ta-S6kS-8vonakhjteaOPQ',
    appId: '1:157280276783:ios:64692788971d6beee251da',
    messagingSenderId: '157280276783',
    projectId: 'quizjatim-2db59',
    storageBucket: 'quizjatim-2db59.firebasestorage.app',
    iosClientId: '157280276783-1fti8qf0jcgpnp9p8skgo0r9becjrp8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizjatimsem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkfFngcy1c1Ta-S6kS-8vonakhjteaOPQ',
    appId: '1:157280276783:ios:64692788971d6beee251da',
    messagingSenderId: '157280276783',
    projectId: 'quizjatim-2db59',
    storageBucket: 'quizjatim-2db59.firebasestorage.app',
    iosClientId: '157280276783-1fti8qf0jcgpnp9p8skgo0r9becjrp8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizjatimsem2',
  );
}
